name: GitHub Action for installing and testing the package on Python 3.11
run-name: pip install and run
on: [ push, pull_request ]
jobs:
  install-and-run-on-python-3-11:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install audiblez
        run: python -m pip install audiblez
      - name: Download model
        run: |
          wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/kokoro-v0_19.onnx
          wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/voices.json
      - name: Check it runs as module
        run: python -m audiblez --help
      - name: check it runs as script
        run: audiblez --help
  install-and-run-on-python-3-12:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install audiblez
        run: python -m pip install audiblez
      - name: Fake download model
        run: touch kokoro-v0_19.onnx && touch voices.json
      - name: Check it runs as module
        run: python -m audiblez --help
      - name: check it runs as script
        run: audiblez --help
#  install-and-run-on-python-3-10: # Doesn't work because of Kokoro
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.10'
#      - name: Install audiblez
#        run: python -m pip install audiblez
#      - name: Fake download model
#        run: touch kokoro-v0_19.onnx && touch voices.json
#      - name: Check it runs as module
#        run: python -m audiblez --help
#      - name: check it runs as script
#        run: audiblez --help
